# .pre-commit-config.yaml
# We use poetry to run formatting and linting before commit/push
# Longer checks such as tests, security and complexity baseline
# are run as part of CI to prevent slower feedback loop
# All checks can be run locally via `make pr`

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: check-merge-conflict
          - id: trailing-whitespace
          - id: check-toml
    - repo: local
      hooks:
          - id: black
            name: formatting::black
            entry: poetry run black
            language: system
            types: [python]
          - id: isort
            name: formatting::isort
            entry: poetry run isort
            language: system
            types: [python]
    - repo: local
      hooks:
          - id: flake8
            name: linting::flake8
            entry: poetry run flake8
            language: system
            types: [python]
