site_name: Rotterdam Cloud Native Meetup sample
site_author: Heitor Lessa
# repo_url: <https://git url>
# edit_uri: edit/develop/docs

nav:
  - Homepage: index.md
  - API reference: api.md

theme:
  name: material
  font:
    text: Ubuntu
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets:
      base_path: "."
      check_paths: true
  - meta
  - toc:
      permalink: true
      toc_depth: 4
  - attr_list
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/policy_masking
      handlers:
        python:
          selection:
            docstring_style: numpy
extra_css:
  - stylesheets/extra.css
